### ISSUE TITLE
Cannot filter field name with "name"

### ISSUE THREAD

**Issue by EraserKing** [patrickTingen/DataDigger#10]
I have some fields whose name includes "name", such as "issue-name".
When I try to filter out these fields by entering "name" in the filter (highlighted in the screenshot below) and press Enter, nothing happens, all the fields are still displayed.
![image](https://user-images.githubusercontent.com/1160403/29961335-ea9873f0-8f31-11e7-9d44-213738e18b92.png)

I guess this is because the caption text "Name" equals to the text "name" I entered, so it thought I didn't enter anything.

**Comment by patrickTingen** [comment]
Hi EraserKing, thanks for reporting this. Your guess is right; I had to code around a lack of something like this in Progress, so when the text entered is the same as the 'shadow text' it is assumed to be not entered. And indeed, sometimes this works out badly

Not sure if I can do something about this, but I will dive into it. At the least it is a nice challenge.

**Comment by patrickTingen** [comment]
Feature looks good now, but I will test it the coming period. It will ship in the next release anyhow
