### ISSUE TITLE
Files seem to be missing from DataDigger26

### ISSUE THREAD

**Issue by dpmuratec** [patrickTingen/DataDigger#104]
There seems to be files missing from the DataDigger26 zips; they only contain .r files.
https://datadigger.wordpress.com/download/ states "Doubleclick datadigger.pf", but there is no datadigger.pf present in the zip.

**Comment by dpmuratec** [comment]
Must have misunderstood how the obj.zips are meant to be used. Source code zips had required files.

**Comment by patrickTingen** [comment]
No problem, please note that the obj zipfile lacks the .wrx file. This is
an omission I am aware of and one that I am going to fix.
In the meantime, you can use the .wrx files from the src zip file. Sorry
for the inconvenience.

*--Patrick Tingen*


Op do 16 mei 2024 om 23:07 schreef dpmuratec ***@***.***>:
