### ISSUE TITLE
Datadigger not compatible with require-field-qualifiers and require-full-names

### ISSUE THREAD

**Issue by movedoa** [patrickTingen/DataDigger#21]
Datadigger can't be compiled when the new strict copiler options are active
There are errors in dQueries.w and wDataDigger.w

**Comment by patrickTingen** [comment]
Hi Movedoa,

Thanks for your report. Actually, last week DD was analyzed by Gilles Querret and he reported over 900 points of interest, including  lot of errors when compiling strict. These will be fixed in DD24

Thanks for your report!

Gr
Patrick

From: movedoa
Sent: maandag 30 oktober 2017 13:03
To: patrickTingen/DataDigger
Cc: Subscribed
Subject: [patrickTingen/DataDigger] Datadigger not compatible withrequire-field-qualifiers and require-full-names (#21)

Datadigger can't be compiled when the new strict copiler options are active
There are errors in dQueries.w and wDataDigger.w

**Comment by patrickTingen** [comment]
Hi Alexander,

I guess I was a little too fast with my promise that 'it would be fixed'.
Apparently there is a bug in OE that results in the UIB generating
abbreviated source. Changing that has no effect; as soon as you change
anything, the UIB regenerates the code. I wrote a blog entry
<https://datadigger.wordpress.com/2017/11/01/too-strict-compile-option/> on
the DD blog on this, check it for more details.


gr
--
Patrick Tingen

**Comment by movedoa** [comment]
Yes i know about this bug and also have deactivated this rule.
But you can still enable "require-field-qualifiers" and "require-full-names" without the keyword rule.

**Comment by movedoa** [comment]
Will require-field-qualifiers" and "require-full-names" be supported in the next release?

**Comment by patrickTingen** [comment]
Yes. The options have been added to DataDigger's own self-compiler, so I should notice when I break something myself. 

I am still thinking of a way to fix the code prior to uploading / compiling so that it could be compiled with the "require-full-keywords" flag as well, but have not decided yet.

**Comment by movedoa** [comment]
Great news, thx

**Comment by patrickTingen** [comment]
Small update: I experimented with fixing the UIB sources prior to compilation, by replacing erroneous statements with correct ones. 

That works, but when I try to open the 'repaired' files in the UIB, it will not open them, giving me errors on the lines I fixed. So I am stuck in a catch-22: if I fix it, I (or the user) cannot maintain them in the UIB anymore, if I don't fix it, I cannot compile with the require-full-keywords flag. 

If you want the sources to be compatible with the require-full-keywords flag and don't mind the UIB-incompatibility, then converting them is not difficult; it takes around 10-15 replace statements on the sources to fix it. If you need help with that, just let me know.

**Comment by movedoa** [comment]
Since we have the same UIB problems we don't use the require-full-keywords flag for now, so for me this is no problem

**Comment by patrickTingen** [comment]
Ok, I'll keep it like it is now then. Thanks again for the report.
