### ISSUE TITLE
Check for PingBack is wrong

### ISSUE THREAD

**Issue by movedoa** [patrickTingen/DataDigger#33]
I guess it should check <> FALSE not <> ? or am i missing something?

![grafik](https://user-images.githubusercontent.com/13309951/44086292-59a2b85a-9fbc-11e8-8a34-d29b8e1c58fd.png)

**Comment by patrickTingen** [comment]
Yes, you are correct. Thanks, I'll fix it

--
Patrick Tingen


Op di 14 aug. 2018 om 12:20 schreef movedoa <notifications@github.com>:

**Comment by patrickTingen** [comment]
Actually, it should check on = TRUE. Otherwise it will also do a pingback when the outcome of getRegistry is unknown ;)

**Comment by patrickTingen** [comment]
Fixed
