### ISSUE TITLE
About Dialog not working correctly

### ISSUE THREAD

**Issue by movedoa** [patrickTingen/DataDigger#34]
(Current dev Version)

The About Dialog is not working.
When i open the Dialog it looks like this:

![grafik](https://user-images.githubusercontent.com/13309951/44202088-4cecb300-a14b-11e8-99b9-a9683c5f6c79.png)

When i close the Dialog and reopen it, i cannot close it anymore with the X, i have to press ESC
When i do this two or three times the About Dialog is embedded into the Main Window

![grafik](https://user-images.githubusercontent.com/13309951/44202169-7dcce800-a14b-11e8-8b32-fd3f8cd5cfad.png)

**Comment by patrickTingen** [comment]
This is a strange bug. The about window does not have any special things like ocx'es or something, just a few images with animation, but that animation is done in plain loops, nothing special.  I tried it in 10.2b / 11.2 and 11.7 64bit and in all three versions it ran spotless.

Could you try again with the current dev version and install it in a separate folder so there are no older files that could be interfering? Easiest way to test is in a simple gui client by running 
RUN c:\path\to\datadigger.p
No database is needed for DD to run

**Comment by patrickTingen** [comment]
Finally fixed in commit 5e5b5c54866818cedde75c86faab1c2d9a273db9
