### ISSUE TITLE
Settings dialog - small visual bugs

### ISSUE THREAD

**Issue by movedoa** [patrickTingen/DataDigger#35]
![grafik](https://user-images.githubusercontent.com/13309951/44202272-c684a100-a14b-11e8-89fa-0c1949d742ff.png)

![grafik](https://user-images.githubusercontent.com/13309951/44202298-dc926180-a14b-11e8-8bfc-e4f0c65c1c9c.png)

![grafik](https://user-images.githubusercontent.com/13309951/44202326-f2a02200-a14b-11e8-8d75-b5a1a4cc5354.png)

**Comment by patrickTingen** [comment]
Could not reproduce the layout here, so might be a version difference.
However, I did find some things that were not set up correctly and also
fixed the labels on the rectangles. They look much better now, without
leading spaces:

[image: image.png]

gr

Patrick Tingen


Op do 16 aug. 2018 om 12:00 schreef movedoa <notifications@github.com>:
