### ISSUE TITLE
Provide a way to disable hints

### ISSUE THREAD

**Issue by movedoa** [patrickTingen/DataDigger#36]
Since i use DD on many different mashines i always get the hints the the first usage of a function.
This wouldn't be so bad but the user is chaning to for some clients, so i get these hints way to often.

It would be nice to have a way to disable hints in general.

**Comment by patrickTingen** [comment]
I added an extra check on the setting 'ShowHints=no'. If you (manually) add
this to the 'DataDigger' section in DataDigger.ini then you will no longer
see any hints.


Patrick Tingen


Op do 16 aug. 2018 om 12:05 schreef movedoa <notifications@github.com>:
