### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by RichardKelters** [patrickTingen/DataDigger#39]
Hi Patrick.

Ik heb gister meteen de laatste beta gedownload en geinstalleerd. Bij deze de compile log:
[DataDigger.log](https://github.com/patrickTingen/DataDigger/files/2351863/DataDigger.log)

Daarna volgt deze error:
![image](https://user-images.githubusercontent.com/23343905/45080145-7cf8f780-b0f4-11e8-9e15-00dc6141eb8a.png)

Vooralsnog lijkt de Digger wel te werken.

Bij deze ook de suggesteerde oplossing die de compile error verhelpt.
(Helaas ondersteund GitHub geen puntpee.)
[DataDiggerLib.txt](https://github.com/patrickTingen/DataDigger/files/2351879/DataDiggerLib.txt)

Groetjes Richard

**Comment by patrickTingen** [comment]
Thanks! Compile error is fixed now

**Comment by patrickTingen** [comment]
Hoi Richard,

Bedankt voor het melden. Het is bekend; gisteravond kreeg ik gelijk al een
melding hiervan. Je had zelf de oplossing al gevonden zie ik. Zal ook nog
even naar die andere rare error in je log ("A variable or array element
passed as an INPUT or INPUT-OUTPUT parameter to a DLL cannot contain the
Unknown value. (12272)")


Met vriendelijke groet,

Patrick Tingen


Op wo 5 sep. 2018 om 10:17 schreef Richard Kelters <notifications@github.com
