### ISSUE TITLE
Window size and buttons

### ISSUE THREAD

**Issue by xtinagp** [patrickTingen/DataDigger#4]
Hello Patrick,

Thank you for this amazing solution to browse Progress' databases. I found some issues with window resizing, both in version 20 and 21. Here's a folder in Dropbox that has a couple of screencasts and my OS description. I hope this helps. Keep up the great coding! 

https://www.dropbox.com/sh/y34rypqbhknk490/AABxfz82T7iHkjPcb6Hv_Tbka?dl=0

**Comment by patrickTingen** [comment]
Hi Christina,

Thanks for using the DataDigger and thanks for your bug report and
screencast. I do have a few questions though. Do you get this behavior all
the time? And if so, are there any particular steps needed to reproduce
this? Another user of DD in your organisation is Rick Taylor. Does he have
this behaviour as well?

The reason I am asking is that I run DD on both win7 and win10 and I only
occasionally have a behavior that looks like this. Progress 4GL is a
challenging language to do nitty gritty resizing things and sometimes I
think they use a randomizer inside the ABL interpreter to generate errors
like this every now and then. Resizing behavior in Progress is not always
fun (for example: just do a search through DD sources for the literal text
"kill kill kill")

Would you mind sending me your DataDigger.log file from the DD folder?
Perhaps this can give me a clue where to start looking.

Again, many thanks for your report and I hope to hear from you soon,

Kind regards

Patrick Tingen

2017-01-06 0:22 GMT+01:00 Cristina Dinchak <notifications@github.com>:

**Comment by xtinagp** [comment]
Hello Patrick.

1. I do get that behavior all the time, specially when dragging the window from one screen to the other.
2. Particular steps to reproduce, hmmm not necessarily. Mainly dragging the window will trigger that behavior. Also resizing.
3. Yes, Rick Taylor and Andrew Fornek get the same issue.
4. I will gather my DataDigger.log tomorrow; we do not have access to github from the office, so I am messaging you from my house. Do you want the log for version 20 or version 21?

I do understand that Progress 4GL has its quirks.. but I am glad there are patient and generous developers like you.

**Comment by patrickTingen** [comment]
No response from user
