### ISSUE TITLE
DB dropdown does not trigger reload table list

### ISSUE THREAD

**Issue by RichardKelters** [patrickTingen/DataDigger#40]
I noticed that after Windows woke up after sleep the selection of another DB in the DB dropdown does not trigger a reload of the table list.

Trying to reproduce it works as expected so it may not have to with WindowsSleep but I cannot put my finger on it.

Windows 10 Pro 64bits 
OE 11.7.2 64bits

**Comment by patrickTingen** [comment]
Same issue on my own pc; if you put your computer to sleep and wake it up, the timer does not seem to work anymore (most of the time). No idea how to fix it, I think it is related to Windows
