### ISSUE TITLE
DataDigger fails to load if wDataDigger.wrx is available

### ISSUE THREAD

**Issue by LMCarlson** [patrickTingen/DataDigger#42]
Receive the following errors when WDataDigger.wrx is available. If it's removed, DataDigger starts as expected.

Is there a fix for this?

Window 10 x64, Progress 11.7.3

![image](https://user-images.githubusercontent.com/17360551/46910036-28267900-cf0b-11e8-8ac8-795ce7da767e.png)

![image](https://user-images.githubusercontent.com/17360551/46910042-53a96380-cf0b-11e8-81e7-830ce9d91eb5.png)

![image](https://user-images.githubusercontent.com/17360551/46910050-6459d980-cf0b-11e8-926b-cbb7da437294.png)

**Comment by patrickTingen** [comment]
When I run DD in 11.7 it runs without any problem, either with or without the .wrx file. 

It probably means that your version of prox.dll is not properly registered. Refer to this KB entry for more information and for instructions on how to fix it: [https://knowledgebase.progress.com/articles/Article/P4138](https://knowledgebase.progress.com/articles/Article/P4138)

**Comment by LMCarlson** [comment]
One correction, I'm running 11.7.2 not 11.7.3.

[DataDigger.log](https://github.com/patrickTingen/DataDigger/files/2479187/DataDigger.log)

**Comment by LMCarlson** [comment]
Once I executed the command in the KB article as administrator, it was fixed. Thank you!
