### ISSUE TITLE
Column filter reset after changing field format

### ISSUE THREAD

**Issue by kingOttmar** [patrickTingen/DataDigger#46]
DD24 / OE 11.6.3

Changing the format in the table-info top-browser will reset query and column filters.

Steps to reproduce:
1. Enter a value in any column filter and execute
2. Change the format for any field in the table-info top-browser
3. Try to re-execute the filter already entered in step 1. by pressing enter in the filter-field (or clicking the execute query play-button)
4. Query and filter is reset.

Column filter fields and query should not reset after changing field format.

**Comment by patrickTingen** [comment]
Hi kingOttmar, thanks for reporting, I'll see if I can fix this.

**Comment by patrickTingen** [comment]
Hi KingOttmar,

I think I've got it fixed. And as a bonus, I found out that I can actually
change the format of the databrowse on the fly, so I do that as well. To
give reporters of a bug credit, I'd like to add you to the changelog. By
what name would you like to appear there?

gr
Patrick Tingen


Op vr 21 dec. 2018 om 11:38 schreef kingOttmar <notifications@github.com>:

**Comment by patrickTingen** [comment]
Fixed in develop branch, will ship with DD25
