### ISSUE TITLE
Generate active record class: syntax for resulting code not correct

### ISSUE THREAD

**Issue by kingOttmar** [patrickTingen/DataDigger#47]
`define public property part       as character no-undo. get. set.`

should be

`define public property part       as character no-undo get. set.`

No "." after no-undo.

**Comment by patrickTingen** [comment]
Thanks for letting me know! I will change it.

--
Patrick Tingen


Op do 7 mrt. 2019 om 13:25 schreef Steven Peeters <notifications@github.com
