### ISSUE TITLE
Table Joins

### ISSUE THREAD

**Issue by johnnyhaff** [patrickTingen/DataDigger#48]
Can an enhancement be added to enable table joins? A lot of times I need to query two tables at once to produce the results I need.

**Comment by patrickTingen** [comment]
Hi Johnny,

Thanks for using DD!

To be honest, I have received requests for table joining more than once,
but it would disrupt too much inside DD to implement it. However, I /am/
thinking of a way to link multiple DD windows to each other, thus enabling
some sort of table joining. The sad part for now is that it is on my
long-list, not my shortlist of things to do.

kind regards,
Patrick Tingen


Op do 7 mrt. 2019 om 15:52 schreef johnnyhaff <notifications@github.com>:

**Comment by johnnyhaff** [comment]
That's too bad, but I understand.
