### ISSUE TITLE
quick connect broken

### ISSUE THREAD

**Issue by SilBoydens** [patrickTingen/DataDigger#49]
in older versions when right clicking in the list of tables before a database was connected, you could select a database relly quickly. in version 24 this trows invallid widget errors
![image](https://user-images.githubusercontent.com/9578499/56655415-fc8f0300-6692-11e9-895d-c11e4614a5d4.png)
stacktrace:
--> selectClickedRow C:/Users/xxx/Desktop/DataDigger-20181003/wDataDigger.w at line 11422  (C:\Users\xxx\Desktop\DataDigger-20181003\wDataDigger.r)
    menuDropDataBrowse C:/Users/xxx/Desktop/DataDigger-20181003/wDataDigger.w at line 9765  (C:\Users\xxx\Desktop\DataDigger-20181003\wDataDigger.r)
    C:/Users/xxx/Desktop/DataDigger-20181003/DataDigger2.p at line 197  (C:\Users\xxx\Desktop\DataDigger-20181003\DataDigger2.r)
    DataDigger.p at line 19  (.\DataDigger.r)

**Comment by SilBoydens** [comment]
screenshot of the older version where it shows a list of recently connected databases
![image](https://user-images.githubusercontent.com/9578499/56655652-ac647080-6693-11e9-8175-cdf6a625b247.png)

**Comment by patrickTingen** [comment]
Hi Sil,

Thanks for using DataDigger and thanks for reporting this. However, when I
test it in my environment, I can see the databases. They have moved one
menu level deeper:

[image: image.png]

Although I did notice a bug: newly added database connections do not show
up until you restart DataDigger.
How is your situation if you restart DataDigger?

Kind regards
Patrick Tingen


Op wo 24 apr. 2019 om 13:20 schreef Sil Boydens <notifications@github.com>:

**Comment by SilBoydens** [comment]
For me the menu doesn't show up untill you went I connections and connected to a DB through there. Once you have connected once then it works, even if you disconnect again it still works. 
Just between starting datadigger and connecting to the first DB it won't work.

I work for a software company so we have hundreds of db's here and datadigger is set to not autoconnect, maybe datadigger autoconnect for you and because of that it doesn't repro the bug

**Comment by patrickTingen** [comment]
Reproduced it, problem is fixed in next version. If you want to fix it in version 24, open wDataDigger.w, locate procedure "menuDropDataBrowse" and insert as first line (right after the variable declarations):

```
IF NOT VALID-HANDLE(ghDataBrowse) THEN RETURN.
```

**Comment by SilBoydens** [comment]
That, will do
