### ISSUE TITLE
Error when try to update/delete record with trigger

### ISSUE THREAD

**Issue by dlabas2** [patrickTingen/DataDigger#51]
When I start DataDigger and try to update a record that has a trigger, the following error occurs:

![image](https://user-images.githubusercontent.com/42679532/70231918-90619b00-175b-11ea-918e-7b63e51bbe0d.png)

After restarting DataDigger in the same session everything works fine.

Thank you very much!!!

**Comment by patrickTingen** [comment]
Hi, thanks for using DataDigger and reporting this issue.

In this case, DataDigger does not have the path to your triggers and cannot
execute them. If you want to change the record without the trigger, you can
uncheck the box at the bottom of the screen:

[image: image.png]
Then DataDigger will skip the trigger.
If you insist on the trigger to fire when you update a record, then make
sure the trigger is in the propath of the session where you run DataDigger.

Kind regards,
Patrick Tingen


Op do 5 dec. 2019 om 12:35 schreef dlabas2 <notifications@github.com>:

**Comment by dlabas2** [comment]
Thank you for your reply.

But in version 24 (20181114) everything works fine. And if in the same session restart DataDiger everything works fine (no PROPATH change).
The error indicates that the database is incorrect.

[cid:fd3db936-25cd-45bf-8b4f-972cbb7a8e69]


:-) Sretno! Good Luck!
     Nemojte se bojati! :-)

Dubravko Labaš<http://aka.ms/weboutlook>
mob. +385 98 9827841

________________________________

**Comment by patrickTingen** [comment]
Then I should probably look into this a bit more. Can you give some more
information on your case?

 - Is your trigger in the propath?
 - Do you use customizations via myDataDigger.p?
 - Is there a delete validation on the record?
 - Do you use DICTDB inside the trigger?

Kind regards
Patrick Tingen


Op do 5 dec. 2019 om 13:11 schreef dlabas2 <notifications@github.com>:

**Comment by dlabas2** [comment]
Hi,



:-) Sretno! Good Luck!
     Nemojte se bojati! :-)

Dubravko Labaš<http://aka.ms/weboutlook>
mob. +385 98 9827841

________________________________

**Comment by patrickTingen** [comment]
Hi Dubravko,

I am looking into this, but I cannot reproduce it. I tried it with a
database with write trigger, with delete trigger, defined inside db and as
separate .p, but everytime the trigger fires.
Since you only experience this the first time you try it, could it be that
there is something else in your session doing something with the dictdb
alias?
I investigated all parts of DD that do something with dictdb, but the truth
is, it are not that many and I cannot find anything wrong with it.

Would it be possible for you to try to reproduce it in a separate session
against the sports db?

Patrick Tingen


Op do 5 dec. 2019 om 15:23 schreef dlabas2 <notifications@github.com>:

**Comment by dlabas2** [comment]
Triggers on base use dictdb alias when logging changes. When does DataDigger first start, this alias dictdb is set to? and then errors occur. When I close DataDigger and restart the alias dictdb is set on the first active database.
The document encloses a modified DataDigger.p program and messages that appear when the program starts. Thank you very much!!!

[DataDigger_DictDb.docx](https://github.com/patrickTingen/DataDigger/files/4034047/DataDigger_DictDb.docx)

**Comment by patrickTingen** [comment]
Thanks for the document. If I look at it, at the point of message 3 it
shows that cDictDb = ?. This surprises me a bit, but I can reproduce it
here.
In the starting program, datadigger.p, this is solved by setting back the
dictdb alias to the same as what it was before DD started, but wile DD is
active, the alias is also not set. I made a change to always set dictdb to
the currently selected database.
If you get the latest version from Github (dev branch), you will have this
change.
Can you check if this will work for you?

Patrick Tingen


Op wo 8 jan. 2020 om 08:35 schreef dlabas2 <notifications@github.com>:

**Comment by dlabas2** [comment]
I checked and everything works fine. Thank you very much!!!

**Comment by patrickTingen** [comment]
You're welcome, and thank /you/  for reporting this.

Cheers!
Patrick Tingen


Op vr 10 jan. 2020 om 09:15 schreef dlabas2 <notifications@github.com>:
