### ISSUE TITLE
Export to Excel

### ISSUE THREAD

**Issue by dlabas2** [patrickTingen/DataDigger#52]
When exporting to Excel using QueryTables, the TextFilePlatform attribute is set to 850. The export result is not good. I changed it temporarily to 1250 and now it's fine. It may be that the code page used is the one offered for export. Thank you.

![image](https://user-images.githubusercontent.com/42679532/72142661-7556fc00-3395-11ea-88d9-d8e45f7c4405.png)

![image](https://user-images.githubusercontent.com/42679532/72142685-7f78fa80-3395-11ea-930c-775372fbf55d.png)

![image](https://user-images.githubusercontent.com/42679532/72142751-aafbe500-3395-11ea-8826-a7a484c64ff3.png)

![image](https://user-images.githubusercontent.com/42679532/72142758-ae8f6c00-3395-11ea-9927-46abda1c5654.png)

**Comment by patrickTingen** [comment]
Thanks for submitting. The cp from the user cannot be used since Excel crashes if you try to export it with a valid codepage like IBM850. It seems to work only with a windows codepage like 1250, 1251 etc. 
I fixed this in the dev branch
