### ISSUE TITLE
Remove RCODE-INFORMATION from TEMP-TABLE definitions

### ISSUE THREAD

**Issue by movedoa** [patrickTingen/DataDigger#53]
The keyword is deprecated and afaik does nothing. Sonar is complaining on our side since we have a rule that checks this.

Just to be clear, this is really just about the keyword in the TEMP-TABLE definitions. The RCODE-INFO system handle is something completely different.

**Comment by patrickTingen** [comment]
Thanks for the info, I did not know that. I will remove it before DD25 is
final

Op di 28 jul. 2020 21:43 schreef movedoa <notifications@github.com>:
