### ISSUE TITLE
Screen-Width 

### ISSUE THREAD

**Issue by tipe** [patrickTingen/DataDigger#55]
In wDataDigger.w - Procedure endResize you set C-Win:WIDTH = 384 (hence this is now the max width)
but I use a screen.resolution with 2560  x 1440, so I disabled this line of code and nothing seems to be broken

**Comment by patrickTingen** [comment]
When I comment the line, start DD and resize it to beyond 384 (1920px), then quit DD and restart it again I get error  **BROWSE brFields does not fit in parent FRAME frMain. (6491). 

I assume you don't get this error? What progress version do you run?

**Comment by tipe** [comment]
no error for me - I'm using 11.6 and 12.2

**Comment by patrickTingen** [comment]
Looking at this again. Since I don't have a monitor with a higher resolution, it's a bit hard to test for me. Could you replace the line you mentioned in endResize with the below one and let me know it that works for you?
````
    /* Set max width */
    C-Win:WIDTH-PIXELS = MINIMUM(C-Win:WIDTH-PIXELS, SESSION:WORK-AREA-WIDTH-PIXELS).

**Comment by tipe** [comment]
Max Screen Width fixed now (tested on 4K screen)
