### ISSUE TITLE
Unknown value to attribute Sensitive on btnFavourite

### ISSUE THREAD

**Issue by curtisschroer** [patrickTingen/DataDigger#57]
When opening the DataDigger app for the first time in the Beta, I am getting this error shown below.  This was without any  database connections in a .pf file.  It seems like when I added the .pf file, I no longer see this error below.
![image](https://user-images.githubusercontent.com/47361501/102627289-ff672300-4115-11eb-8714-84b4382bceed.png)
I am then getting this error right after the first one.  It says ConvertFrom-25 was not found.  I get this no matter if I have database connections defined in a .pf or not.
![image](https://user-images.githubusercontent.com/47361501/102627370-1b6ac480-4116-11eb-89d8-6f1b43329cf0.png)

**Comment by patrickTingen** [comment]
Hi Curtis,

Thanks for letting me know; I published a new release for the
conversion-error. The other one is one I have to take a closer look at.

kind regards
Patrick Tingen


Op vr 18 dec. 2020 om 16:08 schreef curtisschroer <notifications@github.com

**Comment by curtisschroer** [comment]
Hi Patrick,  

Everything seems to work now and I don't get the btnFavourite error anymore.

Thanks for your help,
Curtis
