### ISSUE TITLE
New Option - Generate Temp Table Include

### ISSUE THREAD

**Issue by baltazaroliveira** [patrickTingen/DataDigger#60]
Hello,

I miss a option in to Generate Temp Table Include to generate the type of variable in "short".

Like this:

```
define temp-table ttHl_estadofinanceiro no-undo
  field cp_codigo            as int                  
  field trc_cod              as int                  
  field pagamentos_em_atraso as log                  
  field valor_em_aberto      as dec                  
  field limite_credito       as dec 
  field data_atualizacao     as date.
```

It is possible?

Thanks,
Baltazar

**Comment by patrickTingen** [comment]
Hi Baltazar,

Actually, that's not a bad idea. I don't use it myself (that's probably why
it isn't in already) but I can see the value in that.
I added it to DD26, and for your convenience, find the changed file
attached. Just drop it in the DD folder and start DD again.

Thanks for the idea!

Kind regards
Patrick Tingen


Op ma 18 jan. 2021 om 10:07 schreef baltazaroliveira <
notifications@github.com>:

**Comment by baltazaroliveira** [comment]
Hi Patrick,

Thanks! 

Don´t see the file attached. Can you send?

Baltazar

**Comment by patrickTingen** [comment]
Hi Baltazar,

I really sent it, but I will send it again. In case you still don't see it,
you can also download it from here:
https://raw.githubusercontent.com/patrickTingen/DataDigger/develop/generate-TempTable-Include.w


Kind regards
Patrick Tingen


Op ma 18 jan. 2021 om 12:49 schreef baltazaroliveira <
notifications@github.com>:

**Comment by baltazaroliveira** [comment]
Hi Patrick,

Haven't seen the file.

Have updated the file.

Thanks a Lot
Baltazar
