### ISSUE TITLE
Cannot type umlaut in filter row

### ISSUE THREAD

**Issue by movedoa** [patrickTingen/DataDigger#83]
I cannot type any german "umlaut" like ä or ö or any other special character into the filter row in DD.
As you can see on the screenshot, it works on the other fillins and interesting enough, pasting the character into the field also works.

I suspect this has something to to with the fact that we use UTF-8.

I have found this issue #38 and i tried the change of the triggers.

Changing the trigger from ANY-PRINTABLE to ANY-KEY didn't do anything but changing it to VALUE-CHANGED seems to fix the issue.

**Comment by patrickTingen** [comment]
Hi,

Thanks for reporting this! Do you use the official production version or
the beta version? In my copy of the beta version I can type umlauts:

[image: image.png]


Kind regards
Patrick Tingen


Op di 1 feb. 2022 om 13:47 schreef movedoa ***@***.***>:

**Comment by movedoa** [comment]
I tried the develop version and the problem is still there for me.

This is the pf that i use for DD:

```
-lng GERMAN
-p C:\Editor\DataDigger\Datadigger.p
-mmax 65534
-d dmy
-E
-h 8
-yy 1980
-Bt 2500
-cpstream UTF-8
-cpcase BASIC
-cpinternal UTF-8
-cplog UTF-8
-cpterm UTF-8
-cpcoll BASIC
-filterocxevents
-q
-D 1000
-nb 170
-s 65534
-l 10240
-rereadnolock
-stsh 31
-noautoreslist
-reusableObjects 0
-preloadCLR
-Mr 1012
-tmpbsize 4

```

**Comment by patrickTingen** [comment]
Ah, at least I can reproduce it now. It surely has something to do with the codepage. I will see what I can do.

**Comment by patrickTingen** [comment]
While working on the UTF-8 issues of #84 and #85 I also fixed this one
