### ISSUE TITLE
Error when starting datadigger with UTF-8 and windows username with special characters

### ISSUE THREAD

**Issue by movedoa** [patrickTingen/DataDigger#84]
Windows User "Kùß Ürè-!"

Starting DataDigger results in the following error:

`Invalid character data found in MEMPTR for codepage UTF-8 (12012)`

This happens because DataDigger uses the Ansi Version of the API (GetUserNameA) even when the session is started with UTF-8 codepage. (See https://community.progress.com/s/article/How-to-Call-WIN32-API-Function-GetUserName)

When started with UTF-8 DataDigger should use the W versions of all WinApi calls.
(GetUserNameA, SendMessageA, SetWindowTextA, SetWindowLongA, ....)

**Comment by patrickTingen** [comment]
Thanks for reporting, I'll see if I can replace the A-calls with the
"W"-version

Op wo 13 apr. 2022 om 12:22 schreef movedoa ***@***.***>:

**Comment by patrickTingen** [comment]
I created a local user "Kùß Ürè" on my computer and tested DD in utf-8. It looks good. I also tested a fix for issue #85, please let me know if this works for you

**Comment by patrickTingen** [comment]
I did a new commit for this, so you might want to download the development branch for this to test.

**Comment by movedoa** [comment]
Just tried this on my test mashine and boths fixes (#84 and #85) work. 
Also, this is the first time SokoDigger works with cpinternal UTF-8 :)

Thx for the fix

**Comment by patrickTingen** [comment]
Glad to hear SokoDigger also works. Admit it; that was your goal! :)
(you're not the only one <https://is.gd/stats.php?url=EasterEgg> that plays
it)

Kind regards
Patrick Tingen


Op vr 15 apr. 2022 om 11:44 schreef movedoa ***@***.***>:
